version: '3'
services:
  redis:
    image: redis:latest
    container_name: tc-server
    restart: always
    volumes:
      - ./data/redis:/data
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes